AWSTemplateFormatVersion: 2010-09-09
Description: ELT Test Automation
# Metadata #####################################################################
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VPCCIDR
    ParameterLabels:
      VPCCIDR:
        default: VPC CIDR
# Parameters ###################################################################
Parameters:
  TemplateLocation:
    Description: Location of CloudFormation templates
    Type: String
    Default: https://cf-templates-elt-test-automation.s3-ap-southeast-2.amazonaws.com
    MinLength: 1
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.10.0.0/24
    Description: CIDR block for the VPC
    Type: String
# Conditions ###################################################################
# Resources ####################################################################
Resources:
  NetworkLayer:
    Type: AWS::CloudFormation::Stack
    Properties:
      # NotificationARNs:
      #   - String
      Parameters:
        AvailabilityZones: !Join
          - ','
          - Fn::GetAZs: !Ref AWS::Region
        VPCCIDR: !Ref VPCCIDR
      # Tags:
      #   - Tag
      TemplateURL:
        Fn::Sub: "${TemplateLocation}/network-layer.yaml"
      TimeoutInMinutes: 60
  SecurityLayer:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkLayer
    Properties:
      # NotificationARNs:
      #   - String
      Parameters:
        VPCCIDR: !Ref VPCCIDR
        VPCID: !GetAtt NetworkLayer.Outputs.VPCID
      # Tags:
      #   - Tag
      TemplateURL:
        Fn::Sub: "${TemplateLocation}/security-layer.yaml"
      TimeoutInMinutes: 60
  # DatabaseLayer:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn:
  #     - NetworkLayer
  #     - SecurityLayer
  #   Properties:
  #     # NotificationARNs:
  #     #   - String
  #     Parameters:
  #       PublicSubnet: !GetAtt NetworkLayer.Outputs.PublicSubnet
  #       RDSSecurityGroup: !GetAtt SecurityLayer.Outputs.RDSSecurityGroup
  #     # Tags:
  #     #   - Tag
  #     TemplateURL:
  #       Fn::Sub: "${TemplateLocation}/database-layer.yaml"
  #     TimeoutInMinutes: 60
# Outputs ######################################################################
Outputs:
  NetworkLayerStackRef:
    Value: !Ref NetworkLayer
    Description: Network Layer Stack Reference
  SecurityLayerStackRef:
    Value: !Ref SecurityLayer
    Description: Security Layer Stack Reference
  # DatabaseLayerStackRef:
  #   Value: !Ref DatabaseLayer
  #   Description: Database Layer Stack Reference
